name: tugas_vania
description: Internal package untuk proyek.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # Versi http yang sesuai
  mysql1: ^0.20.0
  vania: ^0.4.0
